# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('netto', models.IntegerField(verbose_name='Нетто')),
                ('delivery_country', models.CharField(max_length=5, verbose_name='Страна доставки')),
                ('vat_rate', models.IntegerField(verbose_name='ставка НДС')),
                ('vat_sum', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='сумма НДС')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
    ]
